### PR TITLE
Test

### PR DESCRIPTION
**Pull request by amberJ99**
I am trying to learn everything about Github so I can help with the implementation of the gap filling techniques. I succesfully pulled the main branch and made a local branch on my computer. I only made a minor change in one of the comments (further in stead of furthur).

### CODE REVIEW

**Comment by amberJ99** [comment]
Normally I would link this pull request with an issue, but because this is only a test I did not make an issue.

**Comment by amberJ99** [comment]
@vergauwenthomas ready for codereview

**Comment by vergauwenthomas** [comment]
@amberJ99 test succeeded!

**Comment by vergauwenthomas** [comment]
this solves #93

**Pull request closed without merging**
